language: python
sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
os:
  - linux
env:
  global:
    - PYTHON=python
    - PIP=pip

matrix:
  include:
    - language: generic
      python: 2.7
      os: osx
      osx_image: xcode7.3
    - language: generic
      python: 3.5
      os: osx
      osx_image: xcode7.3
      env: PYTHON=python3 PIP=pip3

before_install:
  - set -e
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      shell_session_update() { :; }
      if [ "${PYTHON}" = "python3" ]; then
        brew update
        brew install ${PYTHON}
      fi
    fi
#  - ${PIP} install virtualenv
#  - virtualenv venv
#  - source venv/bin/activate
  - ${PIP} install -U pip setuptools
  - ${PYTHON} --version
  - ${PIP} --version
  - ${PYTHON} -c "import setuptools; print(setuptools.__version__)"
install:
  - ${PYTHON} setup.py sdist
  - ${PIP} install dist/bfg9000-0.3.0.dev0.tar.gz
script:
  - 9k --help
