language: python
sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
os:
  - linux
env:
  global:
    - PYTHON=python
    - PIP=pip
    - TEST_COMMAND="test -q"
    - CPPFLAGS="-Wall -Werror"
  matrix:
    - CC=gcc CXX=g++
    - CC=clang CXX=clang++

matrix:
  include:
    - language: generic
      python: 2.7
      os: osx
      osx_image: xcode7.3
      env: CC=clang CXX=clang++ NO_SCALA_TEST=1 NO_GCJ_TEST=1
    - language: generic
      python: 3.5
      os: osx
      osx_image: xcode7.3
      env: CC=clang CXX=clang++ PYTHON=python3 PIP=pip3 NO_SCALA_TEST=1  NO_GCJ_TEST=1
    - python: 2.7
      os: linux
      env: TEST_COMMAND=lint

addons:
  apt:
    packages:
      - default-jdk
      - gfortran
      - gobjc
      - gobjc++
      - gcj-jdk
      - libboost-dev
      - libboost-program-options-dev
      - libogg-dev
      - ninja-build
      - scala
cache:
  - apt

before_install:
  - set -e
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      shell_session_update() { :; }
      brew update
      brew install gcc libogg ninja
      if [ "${PYTHON}" = "python3" ]; then
        brew install ${PYTHON}
      fi
    fi
install:
  - |
    if [ "${TEST_COMMAND}" = "lint" ]; then
      ${PIP} install flake8
    fi
  - ${PIP} install .
script:
  - ${PYTHON} setup.py ${TEST_COMMAND}
